### ISSUE TITLE
jellyfin_ani_sync.UpdateProviderStatus: Video does not contain required index numbers to sync; skipping

### ISSUE THREAD

**Issue by sonicjhon1** [vosmiic/jellyfin-ani-sync#102]
**Describe the bug**
Everytime I marked an episode or a show as complete, I got: `jellyfin_ani_sync.UpdateProviderStatus: Video does not contain required index numbers to sync; skipping`. AniList doesn't seem to update as well because of the error. I've made sure the metadata for the show is present from Jellyfin.

**Logs**
```
jellyfin_ani_sync.UpdateProviderStatus: Video does not contain required index numbers to sync; skipping
jellyfin_ani_sync.UpdateProviderStatus: Video does not contain required index numbers to sync; skipping
jellyfin_ani_sync.UpdateProviderStatus: Video does not contain required index numbers to sync; skipping
```

**To Reproduce**
1. Click on any show
2. Click "Mark as watched" / "Mark as played"
3. See error

**Expected behavior**
Successfully syncs to AniList

**Screenshots**
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/41381685/fee593e9-573a-4479-83e5-189bb36fb8f9)
Episode metadata in Jellyfin.
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/41381685/22893af6-74e2-4c36-994a-1dcc8e11360f)
Show metadata in Jellyfin

**Desktop (please complete the following information):**
 - Firefox 122.0
 - Jellyfin 10.8.13
 - Plugin 3.0.0.0

**Additional context**
I'm using AniList as a tracker.

**Comment by vosmiic** [comment]
Odd. Its unable to find either the season or episode index number, but obviously they are populated (its the season and episode number in that first screenshot). Does this also happen after watching shows, or only when marking them as played?

**Comment by vosmiic** [comment]
I have been able to replicate the issue, will investigate further

**Comment by vosmiic** [comment]
I can only seem to trigger this on shows that have have an "awkward" composition. Are you finding that it is breaking only for this single show or are you hitting into this issue on all of your media?

**Comment by vosmiic** [comment]
I can only seem to trigger this on media that has an "awkward" composition. Are you finding that it is breaking only for this single media or are you hitting into this issue on all of your media?

**Comment by sonicjhon1** [comment]
> Odd. Its unable to find either the season or episode index number, but obviously they are populated (its the season and episode number in that first screenshot). Does this also happen after watching shows, or only when marking them as played?

Sorry for the late reply, but yes. It does happen even after watching the shows.

> I can only seem to trigger this on media that has an "awkward" composition. Are you finding that it is breaking only for this single media or are you hitting into this issue on all of your media?

I've tried multiple media, and all of them seems to be getting this error. I've made sure the season and episode number are both present in Jellyfin too. Could you clarify what an "awkward composition" media is?

**Comment by vosmiic** [comment]
>Could you clarify what an "awkward composition" media is?

What I mean by that is a show that has an odd numbering when it comes to series, or has no real season numbering. But I can see that you are watching a normal show that doesn't have those issues.

I presume this also happens on the non-beta version of the plugin?

**Comment by sonicjhon1** [comment]
> I presume this also happens on the non-beta version of the plugin?
Yes, I've tried with 2.9.0.0 and it happens too.

**Comment by vosmiic** [comment]
I am still investigating this, but am struggling to consistently replicate it. 

Don't think it will help but could you try refreshing your metadata (Scan Library -> Replace all metadata). Do note that this will, as the mode suggests, completely refresh the metadata for the media contained in the library. If you would prefer not to do this I understand.

**Comment by sonicjhon1** [comment]
> Don't think it will help but could you try refreshing your metadata (Scan Library -> Replace all metadata). Do note that this will, as the mode suggests, completely refresh the metadata for the media contained in the library. If you would prefer not to do this I understand.

Hello, I just did this to the entire Library and the plugin works properly now (most of the time). Sometimes it still errors out and doesn't update anilist but after I re-"Replace all metadata" for the Show that is erroring out, it works properly.

**Comment by vosmiic** [comment]
Glad to hear it, probably just some metadata issues then.
