### ISSUE TITLE
Anilist API Manual Sync erroring out.

### ISSUE THREAD

**Issue by macluxHD** [vosmiic/jellyfin-ani-sync#109]
So as already mentioned in my PR #106 users with bigger lists do encounter the error.
During testing I used this users list: https://anilist.co/user/PoXonn/

After looking into it a bit further it is indeed due to some kind of rate limit.
It is kind of strange as if we look at some headers before the rate limited call. After each request this value in the header decreases. So one can clearly see that there should be 60 requests remaining?  Also during testing this always happened after 30 requests.
`
{
X-RateLimit-Limit: 90,
X-RateLimit-Remaining: 60
}
`

But looking at the response from the next API call, we are clearly hitting a rate limit. My guess is that we are just calling the API too fast.
`
{
StatusCode: 429,
ReasonPhrase: 'Too Many Requests'
}
`

So one solution is that we could just increase the amount of time slept between each call. During testing I used 2 seconds and this resolved the issue and I did not hit the rate limit.

Another solution could be to use a different query which I found when looking through the documentation. Using the `MediaListCollection` query the API responds with the whole list in one call. So we would only need to call the API once.  So I propose we replace the current GraphQL query with this one:
```
query ($status: MediaListStatus, $userId: Int) {
  MediaListCollection(userId: $userId, status: $status, type: ANIME) {
    lists {
      entries {
        media {
          siteUrl
        }
        completedAt {
          day
          month
          year
        }
        progress
      }
    }
  }
}
```
This would speed up the retrieval process of the users list and it would not trigger any rate limits.

**Comment by vosmiic** [comment]
Great, thanks for investigating this. I'll make the change and see how I get on, I'll probably also increase the thread sleep time to 2 seconds since this is supposed to work in the background and it shouldn't matter how long it takes. 

I'll also look into adding some re-attempt logic. If we get back a 429 we can attempt the call again after a certain amount of time.

**Comment by vosmiic** [comment]
That PR has been merged now, if you wanted to run the latest version of the plugin you will want to either build it yourself or [docker can build it for you](https://github.com/vosmiic/jellyfin-ani-sync/pkgs/container/jellyfin-ani-sync/191188885?tag=master). These fixes will be included in the next version of the plugin but I'm not sure when that will be released, there are a few other changes I want to add before creating a new release.
