### ISSUE TITLE
Only updating last person to join group in syncplay group

### ISSUE THREAD

**Issue by coderboi342** [vosmiic/jellyfin-ani-sync#11]
Hey pal, I've found that it only updates MAL for the last person to join a syncplay group. It'd be great if you could look into this if possible. Thanks

**Comment by vosmiic** [comment]
We run through each user in PlaybackStopped which is triggered when any media has stopped playing, as seen on this line: https://github.com/vosmiic/jellyfin-ani-sync/blob/54706a411b500aa74c5929ca012f45cd1ac82ce6/ServerEntry.cs#L75
Therefore, all users in a syncplay group should run through the process.
Are all of the users authenticated? Could you perhaps send the server logs when you finish watching something in a syncplay group?

**Comment by coderboi342** [comment]
Yeah, its weird, looks like that should work, but doesn't in my case. Im away from my machine for a few weeks but I'll try to send it over soon. It'd be great if you could try to replicate the issue on your end and see if its unique to me or universal. Thanks again buddy.

**Comment by vosmiic** [comment]
I believe this issue has been fixed in the latest release of Jellyfin, thanks
