### ISSUE TITLE
Update playback status for previously watched items

### ISSUE THREAD

**Issue by Nocifer** [vosmiic/jellyfin-ani-sync#12]
Just a quick question, will this scan for already watched anime and update their playback status on MAL, or will it only work for anime that I watch from now on? That would be a real bummer, because most of my stuff has already been watched back when this nice plugin wasn't yet around... :)

**Comment by vosmiic** [comment]
Hi, unfortunately it only updates MAL after you have actively watched something. 
That being said I will add this to the main project as a possible addition later on down the line, as it seems to be a good feature to add to the plugin.
