### ISSUE TITLE
AniList timeout issue

### ISSUE THREAD

**Issue by vosmiic** [vosmiic/jellyfin-ani-sync#122]
Edit: Yup, the timeout error does indeed still exist too!

_Originally posted by @Jtecx in https://github.com/vosmiic/jellyfin-ani-sync/issues/114#issuecomment-2074605898_

**Comment by vosmiic** [comment]
So I presume you are seeing 429 responses from the API in the logs?
I think there are two solutions to this; I can either create a quick fix that basically increases the timeout between API calls and then upload the plugin here, and you can manually install it. 
Or, if it is suitable, I am planning on properly handling 429's by simply retrying the call after a certain amount of time. 
This is probably going to require a decent amount of dev time and since I am currently unable to work on the plugin this probably won't be out in a beta release until mid to late May.

**Comment by mmshivesh** [comment]
+1 on this issue, have constantly failing requests:

`[2024-04-28 21:59:20.746 -07:00] [ERR] [46] jellyfin_ani_sync.Api.AuthApiCall: Unable to complete AniList API call (POST https://graphql.anilist.co), reason: TooManyRequests; Too Many Requests`

Additionally, could a popup/toast be shown when a "Manual Sync" has started running? This would stop people from clicking multiple times making this problem worse.

**Comment by vosmiic** [comment]
Okay, as a temporary workaround I will extend the timeout and create a new beta release with the fix included.

>Additionally, could a popup/toast be shown when a "Manual Sync" has started running? This would stop people from clicking multiple times making this problem worse.

Yeah I'll look into that.

>This sounds like a good approach, maybe paired with an exponential backoff as well?

Yeah good idea, will add that when I create the proper fix later on.

**Comment by vosmiic** [comment]
So a PR has been created that should fix the AniList timeout issue. Hopefully the PR description explains how it does this, but I can expand on it if anyone is interested.
If anyone would like to test it, a [docker version has been created](https://github.com/vosmiic/jellyfin-ani-sync/pkgs/container/jellyfin-ani-sync/219734503?tag=anilist-timeout-issue), or I can build a version and post it here if anyone does not feel comfortable building it themselves.

**Comment by vosmiic** [comment]
Going to merge the PR which will eventually go into a beta release, hopefully this fixes the timeout issues. Will close this but feel free to re-open if you continue to see the issues in the beta/full release.
