### ISSUE TITLE
Jellyfin 10.9 released

### ISSUE THREAD

**Issue by evoandroidevo** [vosmiic/jellyfin-ani-sync#124]
**Describe the bug**
Jellyfin updated to 10.9 today

**Screenshots**
![image](https://github.com/vosmiic/jellyfin-ani-sync/assets/3161357/78f9a489-c624-49dc-a1f4-c8c49475319c)

**Desktop (please complete the following information):**
 -  firefox
 - 10.9
 - 3.0

**Comment by vosmiic** [comment]
Having a look at the related PR now

**Comment by vosmiic** [comment]
I have released a new version of the plugin that adds support to Jellyfin version 10.9; seems to be taking some time for the manifest changes to appear live on GitHub but it should appear soon

**Comment by Mercedezs** [comment]
I just tested it, it seems to be working perfectly, thank you very much
