### ISSUE TITLE
Can't open select a provider

### ISSUE THREAD

**Issue by AngelAsukii** [vosmiic/jellyfin-ani-sync#126]
Jellyfin Version : 10.9.1

When i click on the list its show this

![image_2024-05-14_043440183](https://github.com/vosmiic/jellyfin-ani-sync/assets/42059981/ff26e6b2-18e5-4d33-8c9e-53061a1fb4d0)

**Comment by vosmiic** [comment]
I can't seem to replicate this issue.
Are you using a browser or a Jellyfin client? I have noticed that when using the Jellyfin media player some elements of the configuration page would not load.

**Comment by AngelAsukii** [comment]
I'm on a web browser, i have tested on Opera GX and Brave, and its the same issue on these 2 browser

**Comment by vosmiic** [comment]
Hmm odd. If you open the developer console and keep an eye on the network requests, you should see a `GET {{YourServer}}/AniSync/parameters` request which returns the provider options when reloading the config page. Is this request being made successfully?

**Comment by AngelAsukii** [comment]
I have this error in my console

![image_2024-05-14_153710904](https://github.com/vosmiic/jellyfin-ani-sync/assets/42059981/213ccbf4-de33-47d1-a220-e7ab13cff32e)

**Comment by vosmiic** [comment]
I am currently making some changes to the frontend, hopefully they should fix your issue

**Comment by vosmiic** [comment]
I can't replicate the issues you are seeing but hopefully the related PR should fix this as it comes with multiple frontend fixes. The fixes will be included in the next beta and full release. Feel free to re-open the issue if you continue to run into issues with the provider list.
