### ISSUE TITLE
Settings seem to be lost on refresh

### ISSUE THREAD

**Issue by vosmiic** [vosmiic/jellyfin-ani-sync#130]
### Discussed in https://github.com/vosmiic/jellyfin-ani-sync/discussions/123

<div type='discussions-op-text'>

<sup>Originally posted by **Qwerty-Space** May  2, 2024</sup>
Hi,

I'm trying to get this plugin working, but every time I go to settings it seems to have forgotten almost everything.
I'm running on archlinux with jellyfin 10.8.13 and ani-sync version 3
</div>

**Comment by khonager** [comment]
specifically the anime list provider is the biggest issue

**Comment by vosmiic** [comment]
> specifically the anime list provider is the biggest issue

Are you seeing the same issue as #126?

**Comment by vosmiic** [comment]
Related PR should fix this. Going to do some final tests and then merge it. The fixes will be included in the next beta release and full release. Feel free to re-open this issue if you continue to see the issues with the config page.
