### ISSUE TITLE
AniSync 3.2.0.0 Status: NotSupported

### ISSUE THREAD

**Issue by wilyub** [vosmiic/jellyfin-ani-sync#133]
**Describe the bug**
The plugin stopped updating my shows on AniList recently. I looked into the plugin section on JellyFin and saw that the plugin has "Status: NotSupported" on it. I believe the plugin was working about a week ago. Any ideas on how to fix?
![anisync](https://github.com/vosmiic/jellyfin-ani-sync/assets/68028075/cb77cb5f-1cd3-45b8-a65e-bf3e0100fe24)

**Logs**
Please provide your Jellyfin logs below. Do not include any private information that may have be contained in the logs.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. firefox, chrome]
 - Jellyfin version [e.g. 10.8]
 - Plugin version [e.g. 2.9]

**Additional context**

**Comment by vosmiic** [comment]
What version of Jellyfin are you running? This is probably due to the fact that I forgot to add the version numbers to the manifest (which has now been fixed: #132).
