### ISSUE TITLE
Unable to authorise MAL login

### ISSUE THREAD

**Issue by thelouisrex** [vosmiic/jellyfin-ani-sync#139]
**Describe the bug**
When trying to set up Ani-Sync, the authorize user is not working. Going to the generated link askes me to login to MAL, but after that the login box flashes and asks me to log in again, the test authentication button returns an error.

**Logs**
[log_20240612.log](https://github.com/user-attachments/files/15808634/log_20240612.log)

**To Reproduce**
1. Go to Ani-Sync Plugin
2. Input Client login information for Provider MAL
3. Click Authorize User, follow link
4. Input Log in information

**Expected behavior**
The user authorization to work.

**Desktop (please complete the following information):**
 - firefox
 - Jellyfin version 10.9.6
 - Plugin version 3.2.0.0

**Comment by vosmiic** [comment]
Check out #77 where they hit into the same problem as you. Most of the time this happens because the redirect URL is incorrect, so I would first check that.

**Comment by thelouisrex** [comment]
Thanks, sorted the issue
