### ISSUE TITLE
Doesn't work behind tunnel

### ISSUE THREAD

**Issue by jeppevinkel** [vosmiic/jellyfin-ani-sync#14]
I'm unsure what exactly is causing it, but the way you fetch the parameters and potentially more parts of the plugin don't work when using a tunnel like what Cloudflare offers. None of the parameters are fetched properly and it results in the config page being unresponsive and missing data.

**Comment by jeppevinkel** [comment]
I just did a test. Even if I complete authentication locally, the rest of the plugin still doesn't work when I connect using my domain. I'm assuming the plugin is attempting to use a local address for communication in the background and that's being tripped by using a public domain instead? Or perhaps it's relying on protocols besides http(s) and/or websockets as those are the only ones operable through a tunnel.

**Comment by vosmiic** [comment]
Unfortunately I did not test the plugin using a remote setup, so I may not be able to help you too much.
The way the plugin settings page communicates with the server is the standard way to do so implemented by the Jellyfin libraries; retrieving data is made by a normal GET request when you initially load the page.
I would first open the console in your browser and check to see what requests are made when you open the plugin settings page and see what kind of response you get. 
If you have authed successfully locally, and the plugin is still not working after watching anime, the Jellyfin logs should give some indication as to where the plugin is going wrong.

**Comment by jeppevinkel** [comment]
That is strange. I don't see anything unusual in the console or the jellyfin logs. I might just try forking the plugin and seeing if I can find the root of the issue over the weekend.

**Comment by vosmiic** [comment]
Were you able to find out why you were experiencing problems? It is odd that you weren't seeing any errors in the logs, as Jellyfin will natively log problems.
