### ISSUE TITLE
API test returns 401

### ISSUE THREAD

**Issue by 46620** [vosmiic/jellyfin-ani-sync#152]
**Describe the bug**
Every time I try to test the API before configuring a client it returns a 401 (blank page in Firefox). 

**Logs**
```
...
jellyfin  | [22:18:40] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [22:18:48] [INF] [34] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [22:19:10] [INF] [34] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
...
```

**To Reproduce**
1. Set API URL
2. Set Callback Redirect URL
3. Save
4. Test API
5. See 401 error

**Expected behavior**
I should see a `"This is the correct URL."`

**Screenshots**
![image](https://github.com/user-attachments/assets/f1ac6404-b57a-4250-9e32-e1630de670f6)
![image](https://github.com/user-attachments/assets/acb39262-0924-469a-a695-d0b57df4d26c)
![image](https://github.com/user-attachments/assets/d1006110-a606-4cb4-8fe9-f8d61913a8bf)

**Desktop (please complete the following information):**
 - Browser: Firefox & Chrome
 - Jellyfin version 10.9.11
 - Plugin version 3.4.0.0

**Additional context**
I tried using the machines local IP, the docker container IP, and the domain IP. They all give a 401.

**Comment by vosmiic** [comment]
I am able to replicate this, presume this was caused by the recent security update and I must have missed adding the ignore auth attribute on this endpoint.
I'll create a hotfix for this, should be simple to fix.
Thanks for reporting it.

**Comment by SadPepeIRL** [comment]
Sorry for the duplicate post @vosmiic I wasn't sure if it was okay to hijack this one with my issue!
Appreciate you following up! <3

**Comment by vosmiic** [comment]
No worries @SadPepeIRL
Thanks for implementing the fix @46620, it will go into a beta build for a bit so if you would like to use a version of the plugin with this fix you will have to [setup your Jellyfin with the beta release repo](https://github.com/vosmiic/jellyfin-ani-sync#development).
