### ISSUE TITLE
Anilist appears to be timing out?

### ISSUE THREAD

**Issue by reitenth** [vosmiic/jellyfin-ani-sync#156]
i click authorize in anilist callback and this pops up after a min or so. ![image](https://github.com/user-attachments/assets/cc5bd133-a005-4416-b935-747f84b9e572)

im running jellyfin linuxserver container on unraid. latest for both jellyfin and the plugin.

all i see in the logs is this ```[2024-09-27 21:53:03.054 -05:00] [ERR] [33] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Could not retrieve AniList token: Unauthorized - Unauthorized". URL "GET" "/AniSync/authCallback".```

**Comment by vosmiic** [comment]
Does the [test endpoint](https://github.com/vosmiic/jellyfin-ani-sync/wiki/Installation-&-Config#api-endpoint) return a confirmation message? (If you aren't on the beta build it might return a 403 instead)

**Comment by reitenth** [comment]
when i run `http://172.19.0.16:8096/AniSync/apiUrlTest` i still get connect has timed out

**Comment by reitenth** [comment]
when i use my `user url` i get `"One or more validation errors occurred."`

**Comment by vosmiic** [comment]
Probably best to use the beta build of the plugin and re-test using the test endpoint. It will let you know which callback URL to use.
