### ISSUE TITLE
Cannot select provider

### ISSUE THREAD

**Issue by shadww** [vosmiic/jellyfin-ani-sync#16]
Jellyfin Version: 10.7.7
Plugin version: 1.6.0.0
Browser tested: Firefox, and Chrome

Issue: When trying to select provider, the drop-down menu is not showing any options.

![image](https://user-images.githubusercontent.com/3989867/170232421-51646a37-0787-4ed1-847c-03022bf11f68.png)

And hence cannot proceed with authorization.

**Comment by vosmiic** [comment]
Do the other drop down boxes show values? Such as the "User" select menu?

**Comment by shadww** [comment]
Yes. User selection drop down menu works, and I can select different users.

**Comment by vosmiic** [comment]
How odd. First off I would advise checking the Jellyfin logs, to see if they give any indication of where the plugin is falling over. Also check the requests made in the browser when loading the plugin config page, the provider list is supplied by the `AniSync/parameters` request. Check to make sure the request is successful.

**Comment by shadww** [comment]
From the logs this is only error I got.
https://pastebin.com/kSpjKxXk

From inspecting the page, console shoots out:
```
GET wss://AAAA.com/jellyfin/socket?api_key=XXXX
[HTTP/1.1 404 Not Found 622ms]

Firefox can’t establish a connection to the server at wss://AAAA.com/jellyfin/socket?api_key=XXXX


main.0f183787a2f78055e856.bundle.js:2 WebSocket connection to 'wss://AAAA.com/jellyfin/socket?api_key=XXXX' failed: Error during WebSocket handshake: Unexpected response code: 404
```
However this is an issue on all pages not only the plugin page.

**Comment by vosmiic** [comment]
I'm getting a feeling this may be related to (I presume) you hosting the Jellyfin instance over the Internet, does this also effect other plugins (if you have any others installed)?

I haven't been able to test the plugin on a hosted Jellyfin instance but I know others have been using it without this specific problem. 

Perhaps if you are able to test if you are still getting the problem when accessing the Jellyfin instance locally. 

Unfortunately I am away from my dev PC so I should be able to have a closer look at the problem on Sunday.

**Comment by shadww** [comment]
I will try to check if I can do this locally.
Other plugins are working fine (at least the ones on the official repo, like trakt for example).

**Comment by vosmiic** [comment]
If other plugins are fine then its probably safe to say that it is a localized problem with this plugin.
I will setup my local instance with a `/jellyfin` path and work on a fix.
I'll keep you updated.

**Comment by vosmiic** [comment]
I believe this issue has now be resolved, it simply required changing some of the hard-coded URLs in the JavaScript to use `ApiClient.getUrl` so the URLs had the correct base URL.
I have tested this in an environment similar to yours (local but I changed the base URL option to append `/jellyfin` to all requests) and the config page is now fully functional.
This is currently live in master, so if you would like to use the changes immediately you will have to build the project yourself.
If you don't need the fixes urgently you could wait until the next release (hard to tell when that will be as I have a few more changes to be made, should be in a few weeks) and then simply update your plugin inside Jellyfin.
Thanks for pointing out the issue, and if you continue to have problems please do let me know.

**Comment by vosmiic** [comment]
Just letting you know that the update that fixes this issue has now been released: https://github.com/vosmiic/jellyfin-ani-sync/releases/tag/v2

If you have installed the plugin via the manifest link, you can simply run the "Update Plugins" task in the "Scheduled Tasks" menu.
