### ISSUE TITLE
Doesn't sync on Android TV.

### ISSUE THREAD

**Issue by SkiingBarroth** [vosmiic/jellyfin-ani-sync#18]
I've noticed that this plugin will not update an anime if I watch it on the Jellyfin Android TV app. It will update if I watch it on my PC using the Jellyfin MPV Shim though. Same user.

**Comment by vosmiic** [comment]
Is the episode marked as completed in Jellyfin after watching it on the Android TV app?
Also are there any entries in the Jellyfin logs after you complete the episode?

**Comment by SkiingBarroth** [comment]
For an episode of teekyuu (an anime with two minute long episodes) I get 

Stopped at "120860" ms

While using mpv shim. It correctly updates MAL and I see the "jellyfin_ani_sync" logs immediately after this episode stop log.

**Comment by SkiingBarroth** [comment]
So, I think it might be an MX player issue. As I watched an episode on my Android TV using LibVLC as the player instead. It updated everything in MAL as it should.
