### ISSUE TITLE
List save location not working?

### ISSUE THREAD

**Issue by Andy2244** [vosmiic/jellyfin-ani-sync#22]
I can not get the save path location to work?

If i try `cache\ani-sync` via settings, i get:
`Error: Could not find a part of the path 'D:\jellyfin\cache\ani-sync\eyjak5cp.3ua'` ?

The issue seems to-be because i started jellyfin-server with the datadir option: `jellyfin.exe --datadir d:\_configs\jellyfin\`
Is there a way to respect this datadir, so i don't have to fully specify the absolute path?

**Comment by Andy2244** [comment]
If i set the save location to this data-dir `d:\_configs\jellyfin\cache\ani-sync` now i get:
`Error: The process cannot access the file 'd:\_configs\jellyfin\cache\ani-sync\qr24kpat.gyk' because it is being used by another process.`

Whats going on here?

**Comment by Andy2244** [comment]
Ok can't get any location to work, even if i try `d:\1`, the plugin creates the temp files, but than gets the same error. The temp files are also than locked by the server, so i cant delete them, without stopping the server.

`Error: The process cannot access the file 'd:\1\pqw0ulxu.lde' because it is being used by another process.`

**Comment by vosmiic** [comment]
Hmm that is odd, you should at least be able to set the file as your Jellyfin data location.
For example, I have it set to `/home/user/.local/share/jellyfin/data` and it works fine.
Let me spin up a Windows VM and see if I get the same result.

**Comment by Andy2244** [comment]
> Hmm that is odd, you should at least be able to set the file as your Jellyfin data location.

Cant get this to work also tried on c: drive via: `c:\Users\andy\AppData\Local\jellyfin\cache\`, again file gets created and i get the access error.

Probably some windows issue, check how your open/create flags on the temp file.

**Comment by vosmiic** [comment]
Weird thing is, is that the check doesn't even do anything that crazy. When you click the test button, it does this:
https://github.com/vosmiic/jellyfin-ani-sync/blob/bb5d038f209ab100aed1022bc0264a0f5c8d7db4/Api/AniSyncController.cs#L46-L52
Which is pretty standard, and should work in both Linux and Windows.
I am still trying to get a Windows VM up and going, could you possibly ignore the error and click save anyway?
Then could you go to "Scheduled Tasks" and manually run the "AniSync Update Anime List" job and see if there are any errors in the logs or confirm the file has actually downloaded.

**Comment by Andy2244** [comment]
> I am still trying to get a Windows VM up and going, could you possibly ignore the error and click save anyway?
> Then could you go to "Scheduled Tasks" and manually run the "AniSync Update Anime List" job and see if there are any errors in the logs or confirm the file has actually downloaded.

Seems to work if i just save, the list gets downloaded at the location. Not sure, does java also need a file.close() call like c++?

I also see a other strange warning if i just partially play a file:
```
Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.8.0 playing Kongming Descends Upon Shibuya. Stopped at 203870 ms
[21:33:42] [WRN] [58] jellyfin_ani_sync.ServerEntry: The user xxx does not have an access or refresh token for AniList. Skipping
```

I also just noticed, maybe we can at least get manually flagged "watched" state working? So if i manually mark a episode watched, can this event be saved and used in the scheduled task?

**Comment by vosmiic** [comment]
>Seems to work if i just save

Okay good, so the error you receive is incorrect on the config page is wrong. Need to see if its limited to just Windows.

>see a other strange warning

Looks like a bug in the log reporting. Shouldn't effect anything, as you have seen it is still updating AniList, but will get that fixed.

>I also just noticed, maybe we can at least get manually flagged "watched" state working? 

I'll have a look and see if we can capture that action via the plugin (can't see why we wouldn't) and get that implemented.

**Comment by vosmiic** [comment]
>Technically the error is correct, since i cant delete the temp file manually either, the plugin seems to still have a open lock handle on it, thats why we get the exception, since delete is failing.

Hmm okay, the file is being deleted on Linux, but I have my Windows VM up and going and I can confirm I am also getting the error. Will try and get this fixed.

>This series was not in any list, so the "found on Completed list" is kinda weird?

Need to have a good look at the entire logging system, looks like its sending all sorts of strange messages.

**Comment by Andy2244** [comment]
ok thanks

btw from my quick tests so far, i got all correct hits. Need to test more complex cases, with very offset episodes.
Yet from all anime scrobble plugins i ever tested, this is now the most accurate and easiest to use, so good job!

Its kinda funny that all those plex anime plugins, need either manually triggered scripts _(Plex removed native plugin support...)_ or only work if everything is correctly renamed to AniDB "mode".

**Comment by vosmiic** [comment]
>Yet from all anime scrobble plugins i ever tested, this is now the most accurate and easiest to use, so good job!

Thanks, without your help though coming up with the new detection changes it wouldn't be anywhere near as accurate as what it is now. So I think you have yourself to thank for a lot of it.

>Its kinda funny that all those plex anime plugins, need either manually triggered scripts (Plex removed native plugin support...) or only work if everything is "correctly" renamed to AniDB "mode".

I haven't actually ran Plex myself, but know some people that do. It sounds like its one of those applications that is easy to setup but very limited, so it doesn't surprise me to hear that plugins don't have as much control as Jellyfin allows. 
Jellyfin is slightly more complicated to setup and get working initially, but once you do have it sorted it seems you can do a lot more with it. I guess thats one of the main benefits of open source software, you can freely modify it to your own liking.

Anyway, I have sorted the anime list save location issues and have tested it on my Windows machine.
I have also found the issue with the logs, but going to do a full check of all logs in an attempt to remove all logging bugs.
After I have fixed the logging issues, going to see if we can update an anime's status after ticking an episode as watched via the interface.

**Comment by Andy2244** [comment]
works now thx
