### ISSUE TITLE
Anilist

### ISSUE THREAD

**Issue by Arial-Z** [vosmiic/jellyfin-ani-sync#3]
Please also consider adding anilist.co support.

Thanks

**Comment by vosmiic** [comment]
Quick update on this, I have been able to implement all of the API calls required by the plugin. Currently I am fitting it into the existing code, after that it should be testing and then release. 

You can keep track of it either via the attached project or the `anilist-support` branch.

**Comment by coderboi342** [comment]
> Quick update on this, I have been able to implement all of the API calls required by the plugin. Currently I am fitting it into the existing code, after that it should be testing and then release.
> 
> You can keep track of it either via the attached project or the `anilist-support` branch.

Thanks man keep up the good werk!

**Comment by vosmiic** [comment]
AniList provider support has now been added to the plugin.

Please update your plugin or download the latest [version](https://github.com/vosmiic/jellyfin-ani-sync/releases/tag/v1.3).

If you hit into any trouble feel free to create a new issue.

**Comment by Arial-Z** [comment]
Thanks a lot, i will add it to my jelly and start testing ;)
