### ISSUE TITLE
Manual sync to AniList not working

### ISSUE THREAD

**Issue by winterbird-code** [vosmiic/jellyfin-ani-sync#33]
I recently created an account on AniList and was really glad to see this feature in jellyfin-ani-sync so that I could populate it. At the moment it doesn't seem to work though, so let's figure out what's wrong :slightly_smiling_face: 

I select the action "update provider with jellyfin progress" and press run. My anilist is not updated, and in the logs I see this:

```
[2022-07-22 09:00:27.790 +02:00] [INF] [53] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Starting sync to provider from local process
[2022-07-22 09:00:27.791 +02:00] [INF] [53] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Retrieved Black Bullet's seasons latest watched episode and when it was watched...
<a few hundred more series>
[2022-07-22 09:00:29.271 +02:00] [INF] [53] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Retrieved Mushishi Zoku Shou's seasons latest watched episode and when it was watched...
```
After that nothing else relevant appears in the log.

## Plugin configuration
I've only configured AniList sync (for one account), and it seems to work fine (the list is updated when I play stuff). Other than the account these settings may be relevant:

- "Ticking watched updates providers?" is set
- "Only change anime in Plan To Watch?" is *not* set
- "Automatically set completed shows as rewatching?" is set
- plugin is configured to only sync from two libraries (one with movies and one with shows; both only contains anime)

**Comment by vosmiic** [comment]
Thanks for posting your logs, the process usually finishes at that point if the selected user does not have the appropriate authentication.
Just to confirm, are you selecting the appropriate user that is authenticated from the drop-down list?

**Comment by winterbird-code** [comment]
Yes, my jellyfin instance has two users, but only one of them are configured to sync. It's the first user so it's selected in the dropdown list by default. Just in case I now tried, before pressing run, to select the other user in the "manual sync"-section dropdown and then re-select the correct user. Same result.

**Comment by vosmiic** [comment]
Hmm that is odd. If there is no other data in the logs (usually there is a wait period involved which is logged) then that makes me think that it is having trouble retrieving all of the needed data from Jellyfin.
The other option is that the shows that are being logged have not been watched in Jellyfin for the selected user, which I presume is not the case here.
Unfortunately I am not able to replicate the issue so it might be tough to figure out where the problem originates from, but I have already seen some mistakes with the new feature that could be causing problems.

**Comment by winterbird-code** [comment]
As you say, everything but a few episodes is marked as watched for my user in jellyfin, so there are plenty of stuff to update.

After fiddling with the log settings I also got these lines after the SyncProviderFromLocal-lines:

```
[2022-07-23 07:52:31.643 +02:00] [INF] [8] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Executed action "jellyfin_ani_sync.Api.AniSyncController.Sync (jellyfin-ani-sync)" in 1582.0257ms
[2022-07-23 07:52:31.643 +02:00] [INF] [8] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executed endpoint '"jellyfin_ani_sync.Api.AniSyncController.Sync (jellyfin-ani-sync)"'
[2022-07-23 07:52:31.643 +02:00] [INF] [8] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.0 POST http://<my-jellyfin-domain>/AniSync/sync?provider=Mal&userId=<some-user-id>&status=Completed&syncAction=UpdateProvider - 0 - 200 0 - 1589.1941ms
[2022-07-23 07:52:31.643 +02:00] [DBG] [8] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMJCDTL5PC7L"" disconnecting.
[2022-07-23 07:52:31.643 +02:00] [DBG] [8] Microsoft.AspNetCore.Server.Kestrel.Connections: Connection id ""0HMJCDTL5PC7L"" stopped.
[2022-07-23 07:52:31.643 +02:00] [DBG] [30] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets: Connection id ""0HMJCDTL5PC7L"" sending FIN because: ""The Socket transport's send loop completed gracefully.""
```

I don't really think it's relevant to this problem, but I notice that the POST-request has provider=Mal (which I assume is MyAnimeList) as parameter, but I have only configured AniList. I managed to "trick" it to use provider=AniList instead by selecting AniList in the provider drop down list before changing action to "update provider". It still didn't sync anything, but I thought I should mention it just in case :)

**Comment by vosmiic** [comment]
>but I notice that the POST-request has provider=Mal

Yeah it ignores the provider and status parameters when updating the provider from the Jellyfin library, so it shouldn't effect it.

I have made some changes to the plugin, but as I am not able to imitate the problem that you are getting would you be comfortable with testing out a new version of the plugin on your end and see if you hit into any trouble?
I can send you a .dll file that is placed in your plugin folder which will overwrite the existing plugin file.

I understand if you aren't comfortable with doing that, and I can release a hotfix with the changes but I won't be able to confirm that it fixes the issues you are experiencing.

**Comment by winterbird-code** [comment]
Sure, I have no problem trying out an experimental dll; feel free to contact me directly at winterbird <at> winterbird.org.

**Comment by vosmiic** [comment]
Sorry, not sure if thats an email - hopefully you don't mind if I throw the dll file in here.
[Here](https://mega.nz/file/MXxVGZ6J#-fcnNUmnldDQHMon0IlU8BGjfZ6hnWDLDwJX44a5chw) is the dll file (alternatively you could build the latest master as it contains all of the potential fixes), and [here](https://jellyfin.org/docs/general/server/plugins/index.html#installing) are the instructions on how to install it, the folder that you will need to replace the dll file in should have a name of `Ani-Sync_2.2.0.0`. If I were you I would keep the old version as a backup just in case though.
Thanks for doing this.

**Comment by winterbird-code** [comment]
Sorry, I didn't check how github would render that..

Anyway, I tried out the new dll, but unfortunately it still didn't work and I find nothing new in the logs. I'm not familiar with .net-code, and have no development environment, but I think I grasp roughly how it's supposed to work looking at [SyncProviderFromLocal.cs](https://github.com/vosmiic/jellyfin-ani-sync/blob/master/Sync/SyncProviderFromLocal.cs).

I can only think that the problem is that GetMaxEpisodeAndCompletedTime returns an empty list, as it looks like all other paths would result in more log entries. Most likely row 85, 87 or 88, but I don't know why. Maybe you could add some useful debug log there?

I double checked the user ID in the POST request, and it matches the ID of my user, although in a different format than what's stored in the database (in the database the id is upper case and has some '-'-separators). Since you already use the user ID earlier in the code to fetch the series (which obviously works) I assume it would break earlier if it was wrong...

My libraries primary use AniDB and AniList for metadata, so everything is just one season (or two if it has any specials), but I don't think that should matter...

**Comment by vosmiic** [comment]
Thanks a lot for testing the dll file, sad to hear that it hasn't fixed anything.

>I can only think that the problem is that GetMaxEpisodeAndCompletedTime returns an empty list

Yeah, I think so too. I made some changes that should have helped but as you have reported it hasn't changed anything. The only possible outcome I believe now is that the plugin is unable to find the episodes that you have watched for each season in the series and so is returning an empty list (as you said), which is troubling. 

>I double checked the user ID in the POST request, and it matches the ID of my user, although in a different format than what's stored in the database (in the database the id is upper case and has some '-'-separators). Since you already use the user ID earlier in the code to fetch the series (which obviously works) I assume it would break earlier if it was wrong...

Yeah it is just parsing your user ID as a GUID. We would have hit some errors earlier if there was a problem in that area.

>My libraries primary use AniDB and AniList for metadata, so everything is just one season (or two if it has any specials), but I don't think that should matter...

Shouldn't be a problem, but AniList and TheTVDB metadata providers have better compatibility with the plugin (generally the best metadata order to set your library's as is TheTVDB at the top, then AniList, then AniDB) but it shouldn't be making a difference at this point.

I have added quite a bit more logging information now (I am thinking of adding a "debugging" checkbox that adds extra details to the log, should help with these situations), unfortunately no fixes as I am still kinda blind, but it would be a great help if you could install this new version and let me know of any new info in your Jellyfin logs: [link](https://mega.nz/file/QCpwiQgK#Ij3NL9_MM5Ahs9mtgOLV8hCgOnQJIwTRIs34dO8X1u8)

**Comment by winterbird-code** [comment]
> > My libraries primary use AniDB and AniList for metadata, so everything is just one season (or two if it has any specials), but I don't think that should matter...
> 
> Shouldn't be a problem, but AniList and TheTVDB metadata providers have better compatibility with the plugin (generally the best metadata order to set your library's as is TheTVDB at the top, then AniList, then AniDB) but it shouldn't be making a difference at this point.

Well, my collection is already organized after AniDB metadata, and changing that would probably be more trouble than it's worth. Also I'm not found of TheTVDB:s arbitrary season breakdown. But back to the issue at hand!
 
> I have added quite a bit more logging information now (I am thinking of adding a "debugging" checkbox that adds extra details to the log, should help with these situations), unfortunately no fixes as I am still kinda blind, but it would be a great help if you could install this new version and let me know of any new info in your Jellyfin logs: [link](https://mega.nz/file/QCpwiQgK#Ij3NL9_MM5Ahs9mtgOLV8hCgOnQJIwTRIs34dO8X1u8)

Yep, we got some interesting logs from that. Turns out it doesn't find any episodes at all in any season. Also, my season names are in Swedish, which probably isn't very common (but probably not related?). This example series should find 25 episodes, all watched.
```
[2022-07-26 06:47:36.871 +02:00] [INF] [33] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Retrieved Log Horizon (2014)'s seasons latest watched episode and when it was watched...
[2022-07-26 06:47:36.871 +02:00] [INF] [33] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Getting Log Horizon (2014) seasons latest watched episode
[2022-07-26 06:47:36.872 +02:00] [INF] [33] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Series Log Horizon (2014) contains 1 seasons
[2022-07-26 06:47:36.872 +02:00] [INF] [33] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Getting user data for Säsong 1 of Log Horizon (2014)...
[2022-07-26 06:47:36.872 +02:00] [INF] [33] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) Season contains 0 episodes
[2022-07-26 06:47:36.872 +02:00] [INF] [33] jellyfin_ani_sync.SyncProviderFromLocal: (Sync) User has watched 0 out of 0 episodes of this season
```

**Comment by vosmiic** [comment]
Hmm I am stumped.
As far as I can tell there should be no reason we cannot retrieve the episodes of a season, I would have thought that if it was breaking anywhere it would be when attempting to retrieve the seasons of a series, not when retrieving the child values of a season (which are always episodes). This kind of feels like it might be a bug outside of this plugin scope since we are using general Jellyfin functions to get the episodes of a season.
I presume it does this for all of your series?
I have changed the way that we retrieve the episodes in this release, but I doubt its going to make much of a difference. You can test it if you still are up to it by installing [this](https://mega.nz/file/4XATxCZB#cpRiFiRZ_F-lkWmUnWuWxWEY8BbG0Ijrze0P0Md15tw) dll file.

**Comment by winterbird-code** [comment]
Thanks, unfortunately it was just as you said: no difference.

This is metadata for one of the episodes (episode 10) for Log Horizon (2014) as received by the jellyfin REST-like API using the jellyfin_apiclient_python library and asking for all video files. I'm not sure if it's any help for you, but maybe it could be useful in case you want to escalate this to the jellyfin project.

```
  {
    "Name": "Guild Master",
    "ServerId": "36c0e5da02704faaadba751481d1ceb6",
    "Id": "b90fe05f364a21feeed93046c66af5b7",
    "HasSubtitles": true,
    "Container": "mkv,webm",
    "PremiereDate": "2014-12-06T00:00:00.0000000Z",
    "Path": "/media/Anime/Series/Log Horizon (2014)/[winterbird] Log Horizon (2014) S1E10 - Guild Master.mkv",
    "OfficialRating": "TV-14",
    "ChannelId": null,
    "CommunityRating": 9,
    "RunTimeTicks": 15623530496,
    "ProductionYear": 2013,
    "IndexNumber": 10,
    "ParentIndexNumber": 1,
    "IsFolder": false,
    "Type": "Episode",
    "ParentLogoItemId": "eb9335ca1ea576691c9bf087f85fb80d",
    "ParentBackdropItemId": "eb9335ca1ea576691c9bf087f85fb80d",
    "ParentBackdropImageTags": [
      "837f7ff4fa526f99c3a5d1858cfe4dc2",
      "74d9e070e6b83effd5e7c1faaf0b08ac",
      "971d941adf0189a065f570be5645daa9",
      "449cd9e7aad2052204681f7e935647b8",
      "1f5b58d816bd84c8f65a116ade16fa86"
    ],
    "UserData": {
      "PlaybackPositionTicks": 0,
      "PlayCount": 2,
      "IsFavorite": false,
      "LastPlayedDate": "2022-07-08T16:50:18.962Z",
      "Played": true,
      "Key": "272128001010"
    },
    "SeriesName": "Log Horizon (2014)",
    "SeriesId": "eb9335ca1ea576691c9bf087f85fb80d",
    "SeasonId": "a573bc1c2f210b1a9b9392457d785c2d",
    "SeriesPrimaryImageTag": "7cc2b8ba965ee0d9a073167f7730d981",
    "SeasonName": "S\u00e4song 1",
    "VideoType": "VideoFile",
    "ImageTags": {
      "Primary": "f2a98eec625be5afe57218f105991126"
    },
    "BackdropImageTags": [],
    "ParentLogoImageTag": "0f45078b45d6cbfb27fdbe80cdc6addf",
    "ImageBlurHashes": {
      "Primary": {
        "f2a98eec625be5afe57218f105991126": "WfJQc60i%0M}Rlf9==EPWUt6R*bFbFs:t6jakBoJt6ayoeafbHa|",
        "7cc2b8ba965ee0d9a073167f7730d981": "dOE3GEof4q-T=;bZaaxFD-kXxbngE5R*ahad9DR*t1Rk"
      },
      "Logo": {
        "0f45078b45d6cbfb27fdbe80cdc6addf": "OK9Q:Pa_R8e?t3k9axoxfjV]azkBj@oe8^j]ogWBt7ofog"
      },
      "Thumb": {
        "ec23de4c839e4b169dfb50837ce10c6d": "NmOM~eRO-=%gt8^,~qoex]%MM{WV?bozWAt7oebH"
      },
      "Backdrop": {
        "837f7ff4fa526f99c3a5d1858cfe4dc2": "WXJRT|-:Xm-:tRo|~CtRr=xGf5en?bxtX8ads-ni~pofs,xtS5a^",
        "74d9e070e6b83effd5e7c1faaf0b08ac": "WcL|.Q%#RjNGo}?b_NksSOs+adRj%#pJt7V?xat7%hkXt7ofofo2",
        "971d941adf0189a065f570be5645daa9": "WRHV6-.TnzS*bd$*AfXURNohxvxaJFNa-nxuJCNe.Ax]-mxuE3M}",
        "449cd9e7aad2052204681f7e935647b8": "WzI;^..8%M?bxuxu~q%Moyxuofe.%NW;RjWCM{V@-;bHofofWAt6",
        "1f5b58d816bd84c8f65a116ade16fa86": "WdK1m}-;xu%2WBt7~qxuoft7M{Rj-=M{t7tRf6jZ?HoLoeayaes:"
      }
    },
    "ParentThumbItemId": "eb9335ca1ea576691c9bf087f85fb80d",
    "ParentThumbImageTag": "ec23de4c839e4b169dfb50837ce10c6d",
    "LocationType": "FileSystem",
    "MediaType": "Video"
  },
```

**Comment by vosmiic** [comment]
It is odd that the API is able to find the references but not our plugin. That makes me now revert what I said and its probably an issue on our end.
Could you share the URL (obviously remove any private details) or the command that you used to get that data? I might be able to reverse engineer the call and work out how the data is retrieved.
Thanks

**Comment by winterbird-code** [comment]
Sure; the actual python code is [here](https://github.com/winterbird-code/adbb/blob/master/adbb/utils.py#L394). The extract above is from a json dump from when I tested this code. The function call returns metadata for *all* video items, so for large instances it can get quite a lot of data. `jf_client` is a initialized and logged in client object from the [jellyfin-apiclient-python library](https://github.com/jellyfin/jellyfin-apiclient-python):

```
    res = jf_client.jellyfin.user_items(params={
            'recursive': True,
            'mediaTypes': [ 'Video' ],
            'collapseBoxSetItems': False,
            'fields': 'Path',
            })
```

 I think the user_items function is just a wrapper around the [/Items](https://api.jellyfin.org/#tag/Items) API endpoint, but I haven't really dug that deep.

**Comment by vosmiic** [comment]
Great, thanks for all of that info.
Haven't touched Python in some time so it probably would have taken me quite a bit longer than you to find the references.
I do get an internal Jellyfin error when attempting to manually make the call (a `Object reference not set to an instance of an object` error) which after looking around seems to be a known issue. I tried the same request on my demo server that I use for development and the call worked. Both use the same Jellyfin version, so kind of odd. Hopefully the issue is unrelated to our problem.
Anyway, I have made a call via the Jellyfin API that successfully gets the required data, and I have tested and it works on my end (although it always has so that doesn't prove much). The call that I made was `http://{{IP:Port}}/Items?userId={{MyJellyfinUserId}}&recursive=true&mediaTypes=Video&api_key={{JellyfinApiKey}}&parentId={{SeriesId}}&parentIndexNumber={{SeasonNumber}}` which returned the episodes of the series, filtered by the season number. 
I have attempted to copy that to the query we use locally:
```
var query = new InternalItemsQuery(_userManager.GetUserById(_userId)) {
                MediaTypes = new []{"Video"},
                ParentId = season.ParentId,
                ParentIndexNumber = season.IndexNumber,
                Recursive = true
            };
```
So I think we have a much better chance of having this work this time since I have directly copied the way Jellyfin makes its own queries.
So if you could please test [this](https://mega.nz/file/oGpXBABa#KP7aE4ccI81sXzZsc1AjNXQVdGnehC80pThbCfCIPkk) dll file that would be a great help.
Thanks

**Comment by winterbird-code** [comment]
Bingo! Thanks, now it syncs as expected!

**Comment by vosmiic** [comment]
Good to hear, thanks for testing all of the dlls, we got there in the end.
I'll create an update for the plugin with the fixes included, you should be okay to keep using that custom dll as Jellyfin should automatically update it.
