### ISSUE TITLE
Plugin fails to recognize correct anime using TheTVDB ID/AniDB and `anime-list-full.xml`

### ISSUE THREAD

**Issue by JoachimFlottorp** [vosmiic/jellyfin-ani-sync#42]
According to the anime-list [README](https://github.com/Anime-Lists/anime-lists/blob/master/README.md#format) the `defaulttvdbseason` attribute can be `0`, `1` or `a` meaning that this line will fail to recognize certain shows such as One Piece.

https://github.com/vosmiic/jellyfin-ani-sync/blob/3cbdc8adfe9735f72553bb2e38a6cbca8e522266/Helpers/AnimeListHelpers.cs#L47

```xml
  <anime anidbid="69" tvdbid="81797" defaulttvdbseason="a">
    <name>One Piece</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-27;2-3;3-9;4-10;5-14;6-0;7-0;8-0;9-0;10-0;11-0;12-0;13-0;14-0;15-0;16-31;17-23;18-24;19-28;20-29;21-30;22-0;23-32;24-34;25-0;26-36;27-37;28-40;29-41;30-42;</mapping>
    </mapping-list>
  </anime>
```

**Comment by vosmiic** [comment]
Thanks for letting me know, I'll try and come up with a fix asap

**Comment by vosmiic** [comment]
I have pushed out a fix for this, please update your plugin. If you continue to see the issue please do let me know and re-open the issue.

**Comment by JoachimFlottorp** [comment]
I can confirm that the latest changes work, thank you for fixing it so quickly.
