### ISSUE TITLE
Client ID/ Client Secret 

### ISSUE THREAD

**Issue by InFerNoBeasTz** [vosmiic/jellyfin-ani-sync#44]
Do I need this? I use anilist. Where do I get Client ID/ Client Secret?

![image](https://user-images.githubusercontent.com/52253277/207715831-a9e2f0b8-10fa-48f4-a236-55bb7265bb4d.png)

**Comment by vosmiic** [comment]
Hi, please read the [wiki](https://github.com/vosmiic/jellyfin-ani-sync/wiki/Installation-&-Config#client-id-and-client-secret) which the plugin has a link to at the top of the plugin settings page to learn how to complete authentication for each provider.
