### ISSUE TITLE
Manually setting show/episode to finished in jellyfin doesn't update watch status on providers.

### ISSUE THREAD

**Issue by Paraxes** [vosmiic/jellyfin-ani-sync#46]
Hey there,
firstly, thank you for the plugin. However I have an issue and I am unsure if it's the intended behavior of the plugin or a limit of jellyfin itself.

If I watch an epsiode normally then syncing progress works just fine, however if I manually set an epsiode to finished within Jellyfin it doesn't syncronize its watched status on Anilist or Myanimelist.

Now, the problem is, that I use jellyfin on my ShieldTV with an external player (If you don't own a ShieldTV: You can basically use the Jellyfin interface but use other players, VLC in my Case, for playback instead of the native Android Exoplayer) because Jellyfin in itself is only capable of downmuxing 5.1 content to stereo but not transcoding 5.1 DTS/DD to a simple 5.1 PCM signal like VLC can. Jellyfin however can not automatically detect the progress of the episode if you use an external player and thus you have to manually set the episode to "finished/watched" after each episode.

Works fine for jellyfin but as described above Anilist/MAL doesn't pick up the watch status then.

Is this something that can be added/fixed?

If not, a simple task scheduler to add the "manually sync progress from jellyfin to the provider" option would be another alternative if this feature can't be implemented easily otherwise. I tried the manual syncing feature and then the correct progress shows up on the providers but obviously an automatic task scheduler would be much preferred in that case.

Thank you very much.

**Comment by vosmiic** [comment]
Hi, there is an option in the plugin settings under the "test save location" button to update the provider after ticking shows as completed. 
![Screenshot_20221218_122744](https://user-images.githubusercontent.com/44092756/208298429-71aa5638-1b8b-4082-a634-094724ffc2d5.png)
This should fulfil the functionality you are looking for. As the little note says, the feature is new and I personally don't use the feature so it has not been heavily tested. 
Also, as a potential fix to your alternative problem, I have been using the [Jellyfin Kodi plugin](https://jellyfin.org/docs/general/clients/kodi/#jellyfin-for-kodi) and it works wonders on my Shield. I found the official Jellyfin app to not work very well (its still being developed so its understandable). Also the Jellyfin Kodi plugin sends the progress update back to Jellyfin, so I don't have to manually tick anything as completed to get the plugin to send the update to the API.
Please do open the issue again if this has not fixed the incident, or if you have any other questions about the plugin.
