### ISSUE TITLE
Video does not contain required index numbers to sync; skipping

### ISSUE THREAD

**Issue by 5TXdYWK** [vosmiic/jellyfin-ani-sync#49]
Getting the following error:
```[ERR] [41] jellyfin_ani_sync.UpdateProviderStatus: Video does not contain required index numbers to sync; skipping```
What exactly does this mean? What am I missing?
Thanks!

**Comment by vosmiic** [comment]
Hi, this means that Jellyfin reports the episode or movie does not have an index number; first I would make sure that the media's metadata has been properly filled by Jellyfin, and then make sure the media has an appropriate season/episode number (if you are attempting to watch and episode of a series) which can be done by editing the metadata of an episode. 
The plugin relies on Jellyfin containing the correct index numbers to know which episode you have watched (the index number will always be `1` when watching a movie).

**Comment by 5TXdYWK** [comment]
Roger, that makes sense. Looks like it's just a matter of setting up my library properly, then! Thanks!
