### ISSUE TITLE
invalid client, cant authenticate 

### ISSUE THREAD

**Issue by reitenth** [vosmiic/jellyfin-ani-sync#5]
i made two api clients in anilist. both redirect urls say this is the correct url but when i try authorizing it always says invalid client. i copy and pasted the client id and secret and both should be correct. my jellyfin server is on my synology if that makes a difference, don't see why it would. maybe it takes some time for anilist to make the api or should it be instant? thanks for your help.

**Comment by vosmiic** [comment]
Hi, you are on the right track in that it is a problem with the redirect URLs. 
Are you connecting to the server over LAN? If so, your redirect URL should look similar to `http://{{IP}}:{{Port}}/AniSync/authCallback` (obviously with your own local IP and Jellyfin port).
I would also make sure that when you generate the authentication URL (after clicking the "Authorize User" button on the config page), the redirect URL contained in the generated URL (should looking something similar to `https://anilist.co/api/v2/oauth/authorize?response_type=code&client_id={{ClientId}}&redirect_uri=http://{{IP}}:{{Port}}/AniSync/authCallback`) matches the one you entered in the AniList client related to the client ID.

**Comment by reitenth** [comment]
thanks for the reply. i had my redirect url in anilist as http://192.168.1.249:8096. once i added /AniSync/authCallback the redirect worked.

**Comment by vosmiic** [comment]
Glad to hear you got it working, in the next update there will be a "Generate Callback URL" button that should help with the confusion
