### ISSUE TITLE
Failing to sync (Request processing error)

### ISSUE THREAD

**Issue by Orski174** [vosmiic/jellyfin-ani-sync#56]
I followed the instructions in the wiki and successfully authenticated my user but when I try to sync the progress in Jellyfin to match AniList it starts the scan and fetches the data then fails? I don't know why this is happening, here's the [log ](https://pastebin.com/MunyJrj5)(the fetch ends at line 2972) because i really can't pinpoint the error that's happening.

**Comment by vosmiic** [comment]
It looks like the request to fetch the anime failed, could be because we hit rate limits or the API server went down. 
I would try running the sync again, the feature is relatively new and as it is kind of buggy.

**Comment by Orski174** [comment]
Ok, will run it again. But shouldn't it make the changes that it fetched to the server? Or it completes the fetch then updates it all at once?
Thank you.

**Comment by vosmiic** [comment]
It first fetches all of the shows and then updates them individually. Depending on how large your library is, it can take a decent amount of time.
