### ISSUE TITLE
[Kitsu Auth Issue] Failing to Authenicate when # inluded in Password

### ISSUE THREAD

**Issue by Middlepepper** [vosmiic/jellyfin-ani-sync#57]
Hi Vosmiic,

I've done some testing and it looks like there something going on with how password are parsed when authenticating for the Kitsu Provider.

It looks like if you have a # or some other special characters in your password it will just off in the URL.

In the below example the log showed my password only before the # and nothing after.

`[2023-01-25 02:09:05.891 +00:00] [ERR] Error processing request: "Could not retrieve Kitsu token: BadRequest - Bad Request". URL "GET" "/AniSync/passwordGrant".`
`[2023-01-25 02:09:05.891 +00:00] [WRN] Slow HTTP Response from "http://**IP ADDRESS**/AniSync/passwordGrant?provider=Kitsu&userId=**USERID**&username=**USERNAME**&password=**PASSWORD**" to "**IP ADDRESS**" in 0:00:05.2603923 with Status Code 401`

After changing my password to remove # it now allows authentication.

**Comment by vosmiic** [comment]
A fix for this has been pushed into master, and will be available in the next release soon
