### ISSUE TITLE
different provider I would like to be supported

### ISSUE THREAD

**Issue by TemmieDola** [vosmiic/jellyfin-ani-sync#59]
https://shikimori.one

**Comment by vosmiic** [comment]
The API looks to support the required calls, I'll add it to my todo list (I am busy with work on other projects though, so it may take me some time to get to work on this)

**Comment by vosmiic** [comment]
This provider has now been added to the plugin on the [appropriate branch](https://github.com/vosmiic/jellyfin-ani-sync/tree/shikimori-support), just need to do some basic testing and then it can be merged to master.

**Comment by vosmiic** [comment]
It has now been merged into master. If you would like the feature now, you can build the plugin manually or wait for the upcoming update to the plugin which will contain the new provider.

If you have any issues with the new provider let me know. I'll be updating the wiki providing support on how to authenticate it.

**Comment by vosmiic** [comment]
So these changes are now in a beta release, which can be added to your local environment by [adding the new beta manifest](https://github.com/vosmiic/jellyfin-ani-sync#development). Like the readme states, both repos can be used at the same time, and any new stable releases will replace the beta releases and vice versa when they become available. 

Don't worry about participating in the beta release if you aren't comfortable with it, if no issues are found it will be promoted to stable in a few weeks once a decent amount of testing has been done. Thanks
