### ISSUE TITLE
Anilist authentication failed

### ISSUE THREAD

**Issue by M3BAID** [vosmiic/jellyfin-ani-sync#65]
error message: {"error":"invalid_client","message":"Client authentication failed"}

**Comment by vosmiic** [comment]
Make sure the client ID is correct, specifically check for trailing spaces

**Comment by BEP0P** [comment]
i got the same issue, how can i make sure its the correct client ID?

**Comment by vosmiic** [comment]
If you have tried the above its hard to say, simply make sure it looks the same as on the website. What API provider are you hitting this issue with?

**Comment by samsolt** [comment]
same issue here, the username is definitely correct

**Comment by ind0r90** [comment]
i got the same error 
"error message: {"error":"invalid_client","message":"Client authentication failed"}"

provider:anilist

**Comment by symphonyalpha** [comment]
I got the same errors as above but resolved it by changing the App Redirect URL. 

For my case, I was running JF within a Docker container alongside Nginx Proxy Manager (didn't expose any ports on the JF container) so I had to set the redirect URL as the IP address that the JF container had in the Docker network and got it to work.

**Comment by vosmiic** [comment]
Thanks for sharing your solution @symphonyalpha. I run my version of Jellyfin on bare metal so I usually can't help users if their Jellyfin is running in a different way to my own.

If anyone keeps getting this same error, please also check the URL that is generated by the plugin. The `client_id` query string should match the one on your Anilist app.

**Comment by M3BAID** [comment]
> i got the same error "error message: {"error":"invalid_client","message":"Client authentication failed"}"
> 
> provider:anilist

Still have the same issue

**Comment by M3BAID** [comment]
> I got the same errors as above but resolved it by changing the App Redirect URL.
> 
> For my case, I was running JF within a Docker container alongside Nginx Proxy Manager (didn't expose any ports on the JF container) so I had to set the redirect URL as the IP address that the JF container had in the Docker network and got it to work.

I'll try this
