### ISSUE TITLE
`MyAnimeList Provider` Once done re-watching a series, the `is_rewatching` flag is not set to false

### ISSUE THREAD

**Issue by JoachimFlottorp** [vosmiic/jellyfin-ani-sync#67]
The API call ignores the contents of the isRewatching flag, and blindly assumes it to be true if the variable is not null, which creates the issue where once you are done watching a series MAL still shows you are rewatching it.

https://github.com/vosmiic/jellyfin-ani-sync/blob/3c9564c93c5ab85c4a3208b21242f9ec52296ca9/Api/Mal/MalApiCalls.cs#L212

**Comment by vosmiic** [comment]
Hmm, that is weird if the API does this. I'll investigate this issue and get back to you.

**Comment by vosmiic** [comment]
Created a new release for this, hopefully it is now fixed. Please do let me know if it isn't
