### ISSUE TITLE
Can't change providers.

### ISSUE THREAD

**Issue by Freakyfox20** [vosmiic/jellyfin-ani-sync#68]
Whenever I change from MyAnimeList to any other provider and save, it automatically reverts back to MAL.

**Comment by PatrickWWork** [comment]
This is probably because it re-fetches the data, therefore lightly reloading the page (or atleast the data on the page). 
Is the data that you enter for the provider saved, or is it wiped?

**Comment by Freakyfox20** [comment]
It's saved.

**Comment by vosmiic** [comment]
Okay, if it saves then I think it's okay to keep it as it is. I'll see if I can get it to stop refreshing the data, but going to treat this as low priority since it doesn't break any functionality. Thanks for letting me know
