### ISSUE TITLE
MyAnimeList Authentication not working

### ISSUE THREAD

**Issue by Hamza-Rafi** [vosmiic/jellyfin-ani-sync#69]
I've set up the MAL app and put the client secret and ID in with no problem. When I go to the authentication link, a javascript alert pops up prompting to put in my MAL username and password. When i put in my details and press enter, the popup reappears. This doesn't stop happening. The javascript console is saying:

`Failed to load resource: the server responded with a status of 401 ()`

**Comment by vosmiic** [comment]
I currently don't have my dev PC available so can't narrow it down to a certain issue, but I have hit this before.

I would check that your redirect URL in the MAL application is correct, other than that please confirm that all of the details you entered are correct.
