### ISSUE TITLE
Not correctly detecting/updating the second cour

### ISSUE THREAD

**Issue by vosmiic** [vosmiic/jellyfin-ani-sync#7]
@reitenth
Bringing this discussion over to GitHub, I find it a bit easier to have a discussion here.
So it seems that AniSync cannot differentiate between different cours of a show; it thinks they are all part of the same season/AniList or MAL show.
At the moment I am working on the Kitsu implementation, but I am nearing the end of the development for it. After I have pushed that out, I will visit this issue and see what can be done.
I am thinking that it will require checking if the episode count in Jellyfin has gone past the detected AniList/MAL shows episode count, and if so checking to see if a separate second cour entry exists in AniList/MAL.
I will keep you updated here on how that goes, but I probably won't be able to visit this until the weekend (at the earliest) unfortunately.

**Comment by reitenth** [comment]
thanks for looking into it, i appreciate how much effort you are putting into this plugin!

**Comment by vosmiic** [comment]
No problem, its quite a new plugin so I'm just trying to iron out all of the small bugs that have slipped through when testing.

In terms of progress, I have been able to find where the plugin is going wrong, and am currently implementing a fix. 
Like I said in my OP, it checks the episode count and compares it to the fetched API anime. If it is larger than the fetched anime, it will mark the fetched anime as complete and attempt to get the next season/cour, and update the progress of the next season/cour to the offset of the first seasons total episode count.

It is going to require quite a bit of testing to make sure it doesn't break any existing functionality, but I am confident I can get it out in the next release (should be in a few days).

**Comment by vosmiic** [comment]
The update that adds support for multi-cour seasons has now been pushed to master, so if you really want to use the new functionality feel free to build off master and add the plugin to your server. 
You could also wait for the next release of the plugin, which like I said above will be soon, just need to make a few much smaller bug fixes.
I think I have thoroughly tested it, but if you find the new functionality acting strangely feel free to create a new issue or post in this one.

**Comment by vosmiic** [comment]
Just an FYI - the new version has now been released (v1.4). Feel free to update via the Jellyfin GUI or by downloading it: https://github.com/vosmiic/jellyfin-ani-sync/releases/tag/v1.4
