### ISSUE TITLE
[Feature Request] Simkl Support

### ISSUE THREAD

**Issue by funforgiven** [vosmiic/jellyfin-ani-sync#71]
It would be really good to consider adding Simkl support. They have a [nicely documented API](https://simkl.docs.apiary.io/). They have many external links on their anime entries so it should be easy to match with TVDB, AniList or MAL ids. Also, there is an active pull request on Sonarr, which allows importing animes from Simkl and this would work nicely to keep Simkl up-to-date.

Actually, there is already a Jellyfin addon for Simkl. However, it depends on the Simkl's recogition using the file name, which does not always work for me. Also, it does not support updating providers on ticking watched and it does not even check watched status. You have to set a watch percentage to scrobble them to Simkl.

**Comment by vosmiic** [comment]
This looks feasible, I'll add it to the list of providers to add support for. Do note I am working on other projects so extending provider support is quite low priority for me, so it may not be available for some time.

**Comment by vosmiic** [comment]
Finally got around to having a look at this. Will keep you updated on my progress.

**Comment by vosmiic** [comment]
I am a little concerned about the 2nd requirement on the API doc:
> 2. The Simkl API is not authorized for use in conjunction with other competing services of the same nature if your service or app does not provide Simkl login and Sync functionality with Simkl, including but not limited to TV, Movie, Anime, Manga list/tracker services. If you are interested in using this service within your own application or website, please contact us at though our Discord and we will be happy to discuss it further!

Since this plugin is focused on supporting a few other tracking services, I believe they won't allow us to support their integration.
Are you able to contact the API team and ask if we are allowed to continue? Feel free to link this PR if it helps.

**Comment by masyk** [comment]
What it means is that you can't use (non tracking) parts of the API without integrating tracking with Simkl option if you also have MAL, etc sync already in your app. The API is specifically designed for plugins like [jellyfin-ani-sync](https://github.com/vosmiic/jellyfin-ani-sync) so you could add tracking for plugins. So you can use it.

It is recommended that you contact the Simkl developers via DM on Discord https://discord.gg/u89XfYn to get your app officially approved and API rate limits removed and to get some one on one help with the API from the Simkl dev team.

**Comment by funforgiven** [comment]
I contacted the developer team on Discord about your concern. I (maybe they) will update you on this. About my understanding of that requirement:

> if your service or app does not provide Simkl login and Sync functionality with Simkl

 I believe it is not a problem since you will provide Sync functionality with Simkl. This requirement is probably to prevent the usage of API just for data purposes (like using it as an alternative to TVDB/TMDB). There is also MAL-Sync which does a really similar thing as your plugin and allowed to use Simkl syncing.

**Comment by masyk** [comment]
Updated the Simkl API docs to make it clearer

**Comment by vosmiic** [comment]
Great, thanks for the clarification @funforgiven and @masyk. Can now continue working on this integration👍 
Also I will reach out on the discord server if I need any assistance.

**Comment by vosmiic** [comment]
Development has mostly finished on this now, just testing it to make sure I haven't missed anything.
As Simkl acts a bit differently to other providers we have, some of the plugins logic has changed when using this provider:

- Rewatching is disabled as Simkl doesn't support it (at least as far as I can tell it doesn't, please do let me know if I am incorrect). If you attempt to rewatch a show/movie, the request simply won't go through and the reason for it will be logged.
- Simkl supports marking episodes as completed individually (unlike others e.g. MyAnimeList which only lets you set the latest episode). A checkbox has been added to the config page to let you choose if you want only the current episode to be marked as watched or all up to the current episode as completed as well. An explanation of how this option effects the behaviour of the plugin will be added to the wiki.

**Comment by vosmiic** [comment]
So these changes are now in a beta release, which can be added to your local environment by [adding the new beta manifest](https://github.com/vosmiic/jellyfin-ani-sync#development). Like the readme states, both repos can be used at the same time, and any new stable releases will replace the beta releases and vice versa when they become available. 

Don't worry about participating in the beta release if you aren't comfortable with it, if no issues are found it will be promoted to stable in a few weeks once a decent amount of testing has been done. Going to close the PR but it can be re-opened if issues related to it are found. Thanks
