### ISSUE TITLE
Question for: Only change shows in Plan To Watch?

### ISSUE THREAD

**Issue by julian100004** [vosmiic/jellyfin-ani-sync#75]
Does ticking that box mean, that the plugin does not update an anime if it is in the "Watching" or any other category besides "Plan To Watch"?

**Comment by vosmiic** [comment]
If you tick the "Only change shows in Plan To Watch" option, only anime that is in the plan to watch OR watching category will be updated. Hopefully that clarifies it, I can understand the confusion.
