### ISSUE TITLE
Jellyfin 10.9 Error

### ISSUE THREAD

**Issue by Flupster** [vosmiic/jellyfin-ani-sync#76]
```System.MissingMethodException: Method not found: 'System.String MediaBrowser.Controller.IServerApplicationHost.GetApiUrlForLocalAccess(MediaBrowser.Common.Net.IPObject, Boolean)'.```

This error prevents the dropdown to select a provider.

I guess the method was removed in 10.9, I can't find any reference to it so hopefully there's an alternative

This plugin is the only reason I'm using Jellyfin, I love it, thanks for making it! [I need to upgrade to 10.9 to fix an issue with VAAPI encoding with complex subtitles causing a glitch ](https://forum.jellyfin.org/t-solved-hwa-amd-vaapi-stuttering)

**Comment by vosmiic** [comment]
Yeah the package reference probably just needs updating, like you said hopefully there's an alternative to the method.

I'll investigate it and hopefully get a new version with the updates out tonight.

>This plugin is the only reason I'm using Jellyfin, I love it, thanks for making it!

Thank you!

**Comment by vosmiic** [comment]
Is there no way that you are able to run the current version? 
Reason I am asking is that compiling it for 10.9 may invoke unknown issues for previous versions as 10.9 hasn't been released yet; I wouldn't want to push it to other users and it potentially break their plugins.
If there is absolutely no way, I could attempt to build it for you locally and upload the experimental .dll for you.

**Comment by Flupster** [comment]
> Is there no way that you are able to run the current version? Reason I am asking is that compiling it for 10.9 may invoke unknown issues for previous versions as 10.9 hasn't been released yet; I wouldn't want to push it to other users and it potentially break their plugins. If there is absolutely no way, I could attempt to build it for you locally and upload the experimental .dll for you.

Is it possible to have a 10.8.x repo and a 10.9.x repo? Eventually people will migrate to the newer version, so at some point there will be a point where half of the community will be on 10.8.x and the other half on 10.9.x

At that point you have to decide which version of Jellyfin to support, the only solution I can see is to have two repo's for the different versions if there is no shared method for both versions.

Another option could be to implement the functionality of the missing method yourself that both versions have access to?

**Comment by vosmiic** [comment]
Seems we have a few ways to approach it, will think of something over the weekend. Will keep you updated with my progress.

**Comment by vosmiic** [comment]
Would you be able to test if anything else is broken on that version? 
Like, if the provider dropdown was working, would you be able to use the plugin without any issues?
If so, it might be easier (although a pain for you) to just manually populate the `<select>` element. 
If you edit the HTML so that the `<select>` with an ID of `selectProvider` has all of the appropriate options, it should let you authenticate. It should look like this:
```
<select is="emby-select" id="selectProvider" name="selectProvider" label="Provider" class="emby-select-withcolor emby-select">
      <option value="Mal">MyAnimeList</option>
      <option value="AniList">AniList</option>
      <option value="Kitsu">Kitsu</option>
      <option value="Annict">Annict</option>
</select>
```
Should be possible by running this in your browser console:
``$('#selectProvider').append($('<option>', { value: 'Mal', text: 'MyAnimeList' }), $('<option>', { value: 'AniList', text: 'AniList' }), $('<option>', { value: 'Kitsu', text: 'Kitsu' }), $('<option>', { value: 'Annict', text: 'Annict' }));``
while on the config page. 
A bit annoying to constantly populate the list (hopefully you don't have to authenticate too many users?) but the devs might restore the `GetApiUrlForLocalAccess` function in the next full release. Hard to believe they would remove such a function.
Of course if it has effected more than just the provider select (more importantly areas that we can't just hack around like above) then we will need to fix the appropriate issues.

**Comment by Flupster** [comment]
Upon clicking authorize user it fails with

```
System.MissingMethodException: Method not found: 'System.String MediaBrowser.Controller.IServerApplicationHost.GetApiUrlForLocalAccess(MediaBrowser.Common.Net.IPObject, Boolean)'.
   at jellyfin_ani_sync.Api.ApiAuthentication..ctor(ApiName provider, IHttpClientFactory httpClientFactory, IServerApplicationHost serverApplicationHost, IHttpContextAccessor httpContextAccessor, ProviderApiAuth overrideProviderApiAuth, String overrideRedirectUrl)
   at jellyfin_ani_sync.Api.AniSyncController.BuildAuthorizeRequestUrl(ApiName provider, String clientId, String clientSecret, String url)
   at lambda_method1222(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

**Comment by vosmiic** [comment]
I believe I have fixed it - could I send you a dll file that you could (temporarily) replace with your current version so you could test it out? I would get a 10.9 version up and running so I could test it myself but my development builds are a bit fragile, and I fear installing a different version may break them.

**Comment by Flupster** [comment]
> I believe I have fixed it - could I send you a dll file that you could (temporarily) replace with your current version so you could test it out? I would get a 10.9 version up and running so I could test it myself but my development builds are a bit fragile, and I fear installing a different version may break them.

I'd be happy to test it out! Throw me a link and I'll test it sometime tomorrow 😁

**Comment by vosmiic** [comment]
Great, thanks!
[Here](https://wormhole.app/Mxl4r#VQK1AuiKWY0-Beedf-M2zw) is a link to the dll file.
Feel free to keep using the file if it works for you, Jellyfin should automatically overwrite it on the next release.
Also [here](https://jellyfin.org/docs/general/server/plugins/#manual) is a quick guide on how to manually install a plugin, in case you need it.

**Comment by Flupster** [comment]
Seems good! Things I tested and worked:

- Generating oauth url 
- Authorizing user 
- Updating series watch progress


```
[18:17:40] [INF] [45] jellyfin_ani_sync.UpdateProviderStatus: (Tvdb) Anime reference found in anime list XML
[18:17:40] [INF] [45] jellyfin_ani_sync.UpdateProviderStatus: Retrieving provider IDs from offline database...
[18:17:40] [INF] [17] jellyfin_ani_sync.UpdateProviderStatus: Retrieved provider IDs
[18:17:40] [INF] [17] jellyfin_ani_sync.UpdateProviderStatus: Using provider AniList...
[18:17:40] [INF] [37] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Series (The Girl I Like Forgot Her Glasses) found on plan to watch list
[18:17:41] [INF] [37] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Updated series (The Girl I Like Forgot Her Glasses) progress to 11
[18:17:41] [INF] [37] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Series (The Girl I Like Forgot Her Glasses) not found in plan to watch list
[18:17:41] [INF] [37] jellyfin_ani_sync.UpdateProviderStatus: (AniList) Series (The Girl I Like Forgot Her Glasses) found, but not on completed or plan to watch list. Skipping
```

Good stuff! Thank you so much, is there anything else specifically you'd like me to test?

**Comment by vosmiic** [comment]
Good to hear, I think you have tested most of the functionality that it could affect.
I'll add the changes I made in that build to the next release, planning on adding a bit more functionality before releasing a final build though.
I'll close the issue, but if you hit into anything else feel free to open it again.
Thanks for using the plugin!
