### ISSUE TITLE
[Feature] / [Question] add missing Series to AniList

### ISSUE THREAD

**Issue by WorldTeacher** [vosmiic/jellyfin-ani-sync#78]
Hey, I have a small question.

Would it be possible to add missing anime to the AniList account?
I sometimes add Anime that are not in my AniList and realize this after the fact or never, which means I am failing at logging everything.

So I was wondering if it was possible to include this functionality into the plugin.

**Comment by vosmiic** [comment]
Setting the ["Only change shows in Plan To Watch?"](https://github.com/vosmiic/jellyfin-ani-sync/wiki/Installation-&-Config#only-change-shows-in-plan-to-watch) setting to false will let the plugin update anime that is not on your plan to watch list.
