### ISSUE TITLE
[Feature Request] Ability to score anime via API

### ISSUE THREAD

**Issue by ashu54-aseem** [vosmiic/jellyfin-ani-sync#80]
Since the plugin already updates the user's anime list, it would be neat if the user could edit or add the score of the anime from Jellyfin itself. MAL at least has the method to update the user's anime list with the score with a patch call.

**Comment by vosmiic** [comment]
Will need to have a look at how difficult it is to manipulate the UI via the plugin, but sure sounds like a good idea. Will get back to you with any updates.

**Comment by vosmiic** [comment]
Had a look at this and unfortunately I don't think this is currently possible, as I don't think plugins can manipulate the UI.
If/when Jellyfin adds support for user rating then we can probably re-open this and investigate how to get it to work with this plugin.
