### ISSUE TITLE
Setting: "Only change anime in Plan to Watch" does not update shows in "Rewatching" on Anilist.

### ISSUE THREAD

**Issue by wilyub** [vosmiic/jellyfin-ani-sync#81]
Hi, thanks for the great plugin. I recently tried rewatching an episode of Fullmetal Alchemist (2003) with the setting "Only change anime in Plan to Watch" on, but it didn't update my list. Afterwards, I changed the setting to off and watched another episode and this pushed an update to my anilist account. Are there any plans to change the above settings functionality to include the "Rewatching" section of anilist (alongside Plan to Watch and Watching) so that I don't need to keep it unchecked? Thanks!

**Comment by vosmiic** [comment]
Yeah that could be an idea, but there are no plans to currently implement it. I'll think about it and see if it is appropriate for the plugin.
Just a quick FYI, its generally quite safe to keep the "Only change anime in Plan to Watch" option off now with the changes to the anime detection. At least I have had it off for quite some time and have hit into only a few occurrences where it incorrectly set the anime, so if you are able deal with the few times it detects the incorrect anime I suggest un-ticking the option.
