### ISSUE TITLE
Anilist error

### ISSUE THREAD

**Issue by Arial-Z** [vosmiic/jellyfin-ani-sync#9]
Hi,

when i try to use anilist i have this error in the jellyfin log :

[2022-03-28 16:01:19.460 +02:00] [WRN] [125] jellyfin_ani_sync.ServerEntry: The user e9f95f59-553a-4a02-8bd8-ba26528145f5 does not have an access or refresh token for AniList. Skipping
[2022-03-28 16:01:19.461 +02:00] [INF] [125] jellyfin_ani_sync.ServerEntry: Using provider AniList...
[2022-03-28 16:01:19.583 +02:00] [WRN] [125] jellyfin_ani_sync.ServerEntry: (AniList) Series not found
[2022-03-28 16:01:19.623 +02:00] [WRN] [88] jellyfin_ani_sync.ServerEntry: (AniList) Series not found

I have setup the app following the installation guide and when i go into the plugin settings and test authentification i got the message saying it's working

Thank you for authenticating *****.

I wiped the config file and switched back to MAL and it's working with MAL which is almost the same setup.

**Comment by vosmiic** [comment]
Hmm you shouldn't have to wipe your config file; the plugin supports multiple services/providers at the same time. 
Could you post the exact name of the media (in Jellyfin) you watched that caused the error? AniList does not need authentication to search so it should still be able to successfully find the media.
Also if you could try re-authenticating, if you have not already tried doing so.
After re-authenticating, could you verify that in the config file the user with an ID of "e9f95f59-553a-4a02-8bd8-ba26528145f5" has a `UserApiAuth` value with a name of `AniList` and the `AccessToken` value is present (please do not post the actual access token string though).

**Comment by Arial-Z** [comment]
no i deleted  jellyfin-ani-sync.xml before switching provider

Here is the config file with removed infos

<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <UserConfig>
    <UserConfig>
      <UserId>e9f95f59-553a-4a02-8bd8-ba26528145f5</UserId>
      <PlanToWatchOnly>false</PlanToWatchOnly>
      <RewatchCompleted>true</RewatchCompleted>
      <UserApiAuth>
        <UserApiAuth>
          <Name>AniList</Name>          <AccessToken>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>
        </UserApiAuth>
      </UserApiAuth>
      <LibraryToCheck>
        <string>ca0de50d2c11073f53df7c82dc3fe2a4</string>
        <string>c1f39650115be79b5cc68387561845de</string>
      </LibraryToCheck>
    </UserConfig>
  </UserConfig>
  <ProviderApiAuth>
    <ProviderApiAuth>
      <Name>AniList</Name>
      <ClientId>XXXX</ClientId>
      <ClientSecret>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</ClientSecret>
    </ProviderApiAuth>
  </ProviderApiAuth>
  <callbackUrl>https://server.url:443</callbackUrl>
  <currentlyAuthenticatingUser>00000000-0000-0000-0000-000000000000</currentlyAuthenticatingUser>
  <currentlyAuthenticatingProvider>AniList</currentlyAuthenticatingProvider>
</PluginConfiguration>


Tested with anime "Seijo no Maryoku wa Bannou Desu" 
[2022-03-28 16:01:19.457 +02:00] [INF] [127] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "\\192.168.1.100\Bibliotheques\Videos\Animes\Animes\Seijo no Maryoku wa Bannou Desu\Seijo no Maryoku wa Bannou Desu\[Cyan] Seijo no Maryoku wa Bannou Desu - 05v2 [WEB 1080p H264 10bit] [AAC] [C463C9DE].mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True

**Comment by Arial-Z** [comment]
yes i may have cut the line too early for `</AccessToken>`
and i'm able to re-authenticate if i revoke the app access in anilist, and test authentification is working fine.

I will try from scratch again tonight, maybe the problem is on my end port 80 is blocked in ufw on the server

**Comment by Arial-Z** [comment]
MAL is working fine so i will just use it
